/**
 * Room code = 6-char lowercase base36, random. Same shape as puzzle codes
 * but a separate namespace (rooms vs puzzles tables, /r/[code] vs /play/[code]
 * URLs). Per docs/DECISIONS.md #0021.
 *
 * Generated by combining 32 bits of crypto-secure randomness, mod 36^6,
 * encoded base36, padded. 36^6 ≈ 2.18B; collisions are caught by the
 * `unique(rooms.code)` constraint and retried by the caller.
 */
const M = 36n ** 6n; // 2_176_782_336

export function generateRoomCode(): string {
  const buf = new Uint8Array(8);
  crypto.getRandomValues(buf);
  let n = 0n;
  for (const b of buf) n = (n << 8n) | BigInt(b);
  n = n % M;
  return n.toString(36).padStart(6, '0');
}

/**
 * Per-player color, drawn from the 8-color palette in [DECISIONS.md #0026].
 * Picks the first slot not already used in the room; if all 8 are taken
 * (shouldn't happen — join-room caps at MAX_PLAYERS = 8) we cycle. The
 * function should never crash on a 9th joiner — that's a join-room concern.
 */
const COLOR_PALETTE = [
  '#f59e0b', // amber-500
  '#0ea5e9', // sky-500
  '#10b981', // emerald-500
  '#f43f5e', // rose-500
  '#8b5cf6', // violet-500
  '#ea580c', // orange-600 (deep, distinct from amber)
  '#14b8a6', // teal-500
  '#d946ef', // fuchsia-500
];

export function nextColor(takenColors: string[]): string {
  for (const c of COLOR_PALETTE) {
    if (!takenColors.includes(c)) return c;
  }
  return COLOR_PALETTE[takenColors.length % COLOR_PALETTE.length]!;
}

export function colorPalette(): readonly string[] {
  return COLOR_PALETTE;
}
