/**
 * Room code = 6-char lowercase base36, random. Same shape as puzzle codes
 * but a separate namespace (rooms vs puzzles tables, /r/[code] vs /play/[code]
 * URLs). Per docs/DECISIONS.md #0021.
 *
 * Generated by combining 32 bits of crypto-secure randomness, mod 36^6,
 * encoded base36, padded. 36^6 ≈ 2.18B; collisions are caught by the
 * `unique(rooms.code)` constraint and retried by the caller.
 */
const M = 36n ** 6n; // 2_176_782_336

export function generateRoomCode(): string {
  const buf = new Uint8Array(8);
  crypto.getRandomValues(buf);
  let n = 0n;
  for (const b of buf) n = (n << 8n) | BigInt(b);
  n = n % M;
  return n.toString(36).padStart(6, '0');
}

/**
 * Auto-assign a color to a new room player. Cycles through a 4-color palette;
 * if 4 players are present, we return the next-in-cycle (visual collision but
 * never a crash). The Edge Function should also refuse a 5th joiner.
 */
const COLOR_PALETTE = [
  '#f59e0b', // amber-500
  '#0ea5e9', // sky-500
  '#10b981', // emerald-500
  '#f43f5e', // rose-500
];

export function nextColor(takenColors: string[]): string {
  for (const c of COLOR_PALETTE) {
    if (!takenColors.includes(c)) return c;
  }
  return COLOR_PALETTE[takenColors.length % COLOR_PALETTE.length]!;
}

export function colorPalette(): readonly string[] {
  return COLOR_PALETTE;
}
